### ISSUE TITLE
Configuration details within Deployment section

### ISSUE THREAD

**Issue by vitaliy0x1** [Velocidex/velociraptor-docs#420]
Hi Guys!
I miss some kind of a reference page about the Config file in documentation. 
I've started to create it. But before I proceed, I would like to know your thoughts about it. 
Here is 2 screenshots how I see it [1](https://user-images.githubusercontent.com/9745163/198680373-314e41b2-a5f9-4f9f-b727-96e6882274dd.jpg), [2](https://user-images.githubusercontent.com/9745163/198680366-cf7b72e5-29c3-4e48-947e-14ca2da92a90.jpg)
I used [this file](https://github.com/Velocidex/velociraptor/blob/de20717b9e15d1ff747ffeb16a7c53fe8de4c57a/docs/references/server.config.yaml)  as a source, but I'm not sure if it actually enough. For me, it is more convenient to show examples and attach links within the Documentation.  

Do we need it or such reference can be created in some automated way with fewer efforts?

**Comment by scudette** [comment]
The plan is to use the file you referenced as a source to build the html page somehow. Probably we will build a markdown page and use the normal template to fit in with the web page.

I do like your design idea so if you can come up with the css and classes we can start to work on the converter?

**Comment by vitaliy0x1** [comment]
I played a bit with CSS and come up with this for `theme-mine.css` file.

```css
.reference {
    font-family: monospace, Consolas, Courier Prime, Courier, Courier New;
} 
.reference.top {
    font-size: 1.8rem;
} 
.reference.middle {
    padding-left: 25px;
    font-size: 1.3rem;
} 
.reference-details {
    padding-left: 50px;
    display: block;
    line-height: 1.7;
} 
```
In Hugo it will be something like this
```
## <span class='reference top'>API</span>  
<span class='reference middle'>hostname</span>  
<span class='reference-details'>
**Description**: Description here
**Required**: Yes  
**Example values**: `velo.corp.lan` | `192.168.1.10`  
</span>
```
And as a result it looks like this [this](https://user-images.githubusercontent.com/9745163/198872611-ad8e3479-88e1-48f0-ad45-eb483a710853.jpg).

@scudette you mean one more Python script as we have in `velociraptor-docs/scripts/` folder? 
If so, I can make it, it should not take long.
